#!/bin/sh

blessings=(
"In nomine Patris, et Filii, et Spiritus Sancti, sub divinae tutelae potentia te ponimus. Custos angelorum te defendat et custodiat, teque ab omni malo tueatur. Amen."
"Dominus benedicat et custodiat te; Dominus ostendat faciem suam tibi et misereatur tui; Dominus convertat vultum suum ad te et det tibi pacem. Amen."
"Sub alis Altissimi te custodiat et protegat. Amen."
"Per intercessionem Sanctae Mariae, Matris Dei, te custodiat et protegat. Amen."
"Per intercessionem Sancti Michaelis Archangeli, defendat te in proelio, contra nequitiam et insidias diaboli esto praesidium. Amen."
"Angele Dei, qui custos es mei, me tibi commissum pietate superna, illumina, custodi, rege, et guberna. Amen."
"Sub umbra alarum tuorum, Domine, protege nos. Amen."
"Benedicat et custodiat te Dominus omnipotens, qui fecit caelum et terram. Amen."
"Ad te confugimus, sancta Dei Genetrix. Nostras deprecationes ne despicias in necessitatibus, sed a periculis cunctis libera nos semper, Virgo gloriosa et benedicta. Amen."
"Sanctus Spiritus, veni in auxilium nostrum. Emitte caelitus lucis tuae radium. Amen."
)
blessings_count=${#blessings[@]}

currentBranch=$(git symbolic-ref --short -q HEAD)

changes_names=$(git diff --cached --name-only --numstat)
changes_count=$(git diff --cached --numstat | wc -l)

if [ $changes_count -eq 0 ];
then
    echo "✝ Nothing to bless. Have a blessing for your future code:"
    sleep 0.4
    echo "✝✝✝ ${blessings[$(($RANDOM % $blessings_count))]} ✝✝✝"
    exit 0
fi

# complex science-based stuff for it to sound legit
blessings_needed=$(echo "l(${changes_count})/l(2)"| bc -l)

# any change deserves some amount of blessing
if [ $(printf "%.${2:-0}f" $blessings_needed) -eq 0 ];
then
    blessings_needed=`echo "scale=4; $(( ($RANDOM % 1000) + 1)) / 1000" | bc`
fi

formatted_blessings_needed=`printf "%1.4f" $blessings_needed`
rounded_blessings=$(printf "%.${2:-0}f" $blessings_needed)
min_blessings=$(( 1 > $rounded_blessings ? 1 : $rounded_blessings ))

echo "✝ Blessing $changes_count changed files."
echo "✝ Estimated number of blessings required: ${formatted_blessings_needed}."
echo "✝ Blessing ${min_blessings} times to be safe."

# make it seem customized
echo "✝ Blessing: "
for f in $changes_names
do
    echo "\t$f"
done

echo ""

for i in `seq 1 $min_blessings`
do
    # need to make it look like hard work
    sleep 0.4
    blessing=${blessings[$(($RANDOM % $blessings_count))]}
    echo "✝✝✝ $blessing ✝✝✝"
    echo ""
    if [ ! -z "${1}" ] && [[ "-v" -eq "${1}" ]] 
    then
        say -v Cellos $blessing
    fi
done


echo "✝ Done. The following changes have been blessed:"
for f in $changes_names
do
    echo "\t✝ $f"
done

# call to action
echo "✝ You can now safely commit these files."
